# Generated by Django 4.0.5 on 2022-08-10 19:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POSTEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Subtitulo', models.CharField(max_length=30)),
                ('Cuerpo', ckeditor.fields.RichTextField()),
                ('Autor', models.CharField(max_length=30)),
                ('Born', models.DateField()),
            ],
        ),
    ]
